
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'en' | 'vi';

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.connections': 'Connections',
        'nav.tables': 'Data Assets',
        'nav.reports': 'Ask AI',
        'nav.bi': 'Dashboard Studio',
        'nav.ai_config': 'AI Settings',
        'nav.users': 'Users',
        'nav.sign_out': 'Sign Out',
        'nav.locked_tooltip': 'Add a connection first',
        'sys.status': 'System Status',
        'sys.active': 'Pipeline established. AI analysis active.',
        'sys.pending': 'Neural link pending. Connect your data warehouse.',
        'conn.title': 'Data Gateways',
        'conn.subtitle': 'Provision secure pipelines to your enterprise data warehouses',
        'conn.search_placeholder': 'Search gateways...',
        'conn.new_pipeline': 'New Pipeline',
        'conn.stat.total_connections': 'Total Connections',
        'conn.stat.active_syncs': 'Active Syncs',
        'conn.stat.total_tables': 'Linked Tables',
        'conn.stat.system_health': 'System Health',
        'conn.empty_title': 'No Connections Found',
        'conn.empty_subtitle': 'Start by connecting your first data source. We support BigQuery, Snowflake, and more to bring your data to life.',
        'conn.empty_button': 'Get Started Now',
        'conn.card.health': 'Health',
        'conn.card.optimal': 'Optimal',
        'conn.card.objects': 'Objects',
        'conn.wizard.step1': 'Configure Gateway',
        'conn.wizard.step2': 'Identity Verification',
        'conn.wizard.step3': 'Target Environment',
        'conn.wizard.step4': 'Object Selection',
        'reports.new_chat': 'New AI Analysis',
        'reports.placeholder': 'Ask AI to generate a report, e.g. "Revenue trend by category"',
        'reports.strategic_summary': 'Strategic Executive Summary',
        'reports.analysis': 'Root Cause & Data Analysis',
        'reports.recommendation': 'Recommended Actions',
        'reports.visualization_layer': 'Precision Visualization Layer',
        'reports.export': 'Export Report',
        'reports.strategic_flow': 'Strategic Flow',
        'reports.grid_view': 'Grid View',
        'reports.share': 'Share Insight',
        'reports.engine_title': 'Neural Analysis Engine',
        'reports.engine_subtitle': 'Precision BigQuery analysis. Automatically links time trends and categorical dimensions for instant visualization.',
        'bi.visualizations': 'Visualizations',
        'bi.data': 'Data Views',
        'bi.format': 'Design & Style',
        'bi.filters': 'Dashboard Filters',
        'bi.visuals': 'Visuals',
        'bi.config': 'Config',
        'bi.setup': 'Setup',
        'bi.format_tab': 'Format',
        'bi.filters_tab': 'Filters',
        'bi.active_table': 'Active Table',
        'bi.select_table': 'Select data table...',
        'bi.new_widget': 'New Widget',
        'bi.kpi_card': 'KPI Card',
        'bi.data_table': 'Data Table',
        'bi.slicer': 'Slicer',
        'bi.date_range': 'Date Range',
        'bi.search': 'Search Box',
        'bi.no_widget_selected': 'No Widget Selected',
        'bi.no_widget_selected_desc': 'Select a widget on the canvas to configure its data fields and logic.',
        'bi.no_data_source': 'No Data Source',
        'bi.no_data_source_desc': 'Assign a data table to this widget in the Visuals tab.',
        'bi.select_data_table_btn': 'Select Data Table',
        'bi.data_fields': 'Data Fields',
        'bi.source': 'Source',
        'bi.change_source': 'Change Data Source',
        'bi.cross_filtering': 'ENABLE CROSS-FILTERING',
        'bi.title': 'Title',
        'bi.value_format': 'Value Format (Axis)',
        'bi.show_legend': 'Show Legend',
        'bi.legend_position': 'Position',
        'bi.show_grid': 'Show Grid',
        'bi.show_labels': 'Show Labels',
        'bi.typography': 'Typography',
        'bi.font_family': 'Font Family',
        'bi.font_size': 'Font Size',
        'bi.border_shadow': 'Border & Shadow',
        'bi.border_radius': 'Border Radius',
        'bi.show_shadow': 'Show Shadow',
        'bi.chart_colors': 'Chart Colors',
        'bi.reset_palette': 'Reset to Default Palette',
        'bi.widget_filters': 'Widget Filters',
        'bi.add_filter': 'Add Filter',
        'bi.no_filters': 'No filters applied',
        'bi.saving': 'Saving...',
        'bi.auto_saved': 'Auto-saved',
        'bi.clear_filters': 'Clear Filters',
        'bi.back_to_list': 'Back to List',
        'bi.undo': 'Undo',
        'bi.redo': 'Redo',
        'bi.reload_data': 'Reload Data',
        'bi.auto_reload_settings': 'Auto-reload Settings',
        'bi.disabled': 'Disabled',
        'bi.every_min': 'Every {mins} min',
        'bi.every_mins': 'Every {mins} mins',
        'bi.export_pdf': 'Export PDF',
        'bi.export_image': 'Export Image',
        'bi.toggle_visual_builder': 'Toggle Visual Builder',
        'bi.workspace': 'Workspace',
        'bi.fields': 'Fields',
        'bi.dashboards_title': 'Dashboards',
        'bi.unfiled': 'Unfiled',
        'bi.new_folder': 'New Folder',
        'bi.new_dashboard': 'New Dashboard',
        'bi.confirm_delete': 'Confirm Delete',
        'bi.delete_desc': 'Are you sure you want to delete "{title}"? This cannot be undone.',
        'bi.delete_btn': 'DELETE',
        'bi.cancel_btn': 'CANCEL',
        'bi.folder_name_placeholder': 'Folder name...',
        'bi.move_to_root': 'Move to root',
        'bi.add_calc_field': 'Calculated Fields',
        'bi.add_btn': 'ADD',
        'bi.save_btn': 'Save',
        'bi.cancel_small': 'Cancel',
        'bi.quick_measures': 'Quick Measures',
        'bi.selection_mode': 'Selection Mode',
        'bi.multi_select': 'Multiple Selection',
        'bi.single_select': 'Single Selection',
        'bi.global_filter_bar': 'Global Filter Bar',
        'bi.pin_to_top': 'Pin to top of report',
        'bi.dropdown_mode': 'Dropdown Mode',
        'bi.compact_view': 'Compact selection view',
        'bi.show_select_all': 'Show "Select All"',
        'bi.quick_toggle': 'Quickly toggle all options',
        'bi.series': 'Series',
        'bi.default': 'Default',
        'bi.no_widget_selected_desc_start': 'Select a widget on the canvas to configure its',
        'bi.config_data': 'data',
        'bi.style': 'style',
        'bi.welcome': 'Welcome to Dashboard Studio',
        'bi.create_new_dashboard': 'Create New Dashboard',
        'bi.collapse_left_panel': 'Collapse Left Panel',
        'bi.expand_left_panel': 'Expand Left Panel',
        'bi.collapse_right_panel': 'Collapse Right Panel',
        'bi.expand_right_panel': 'Expand Right Panel',
        'bi.filters_label': 'Filters',
        'bi.move_to_canvas': 'Move back to Canvas',
        'bi.add_from_canvas': 'Add filter from Canvas',
        'bi.add_btn_small': 'Add',
        'bi.duplicate_page': 'Duplicate Page',
        'bi.delete_page': 'Delete Page',
        'bi.add_new_page': 'Add New Page',
        'bi.delete_page_desc': 'Are you sure you want to delete page "{title}"? All widgets on this page will be removed. This cannot be undone.',
    },
    vi: {
        'nav.connections': 'Kết nối',
        'nav.tables': 'Tài sản dữ liệu',
        'nav.reports': 'Hỏi đáp AI',
        'nav.bi': 'Thiết kế Dashboard',
        'nav.ai_config': 'Cài đặt AI',
        'nav.users': 'Người dùng',
        'nav.sign_out': 'Đăng xuất',
        'nav.locked_tooltip': 'Vui lòng thêm kết nối trước',
        'sys.status': 'Trạng thái hệ thống',
        'sys.active': 'Đường ống đã thiết lập. AI đang phân tích.',
        'sys.pending': 'Chờ kết nối. Vui lòng kết nối kho dữ liệu.',
        'conn.title': 'Cổng kết nối dữ liệu',
        'conn.subtitle': 'Thiết lập các đường ống dữ liệu bảo mật tới kho dữ liệu của doanh nghiệp',
        'conn.search_placeholder': 'Tìm kiếm kết nối...',
        'conn.new_pipeline': 'Kết nối mới',
        'conn.stat.total_connections': 'Tổng số kết nối',
        'conn.stat.active_syncs': 'Đang đồng bộ',
        'conn.stat.total_tables': 'Số lượng bảng',
        'conn.stat.system_health': 'Tình trạng hệ thống',
        'conn.empty_title': 'Chưa có kết nối nào',
        'conn.empty_subtitle': 'Bắt đầu bằng cách kết nối với nguồn dữ liệu đầu tiên của bạn. Chúng tôi hỗ trợ BigQuery, Snowflake và nhiều nguồn khác.',
        'conn.empty_button': 'Bắt đầu ngay',
        'conn.card.health': 'Trạng thái',
        'conn.card.optimal': 'Hoạt động tốt',
        'conn.card.objects': 'Đối tượng',
        'conn.wizard.step1': 'Cấu hình kết nối',
        'conn.wizard.step2': 'Xác thực danh tính',
        'conn.wizard.step3': 'Môi trường mục tiêu',
        'conn.wizard.step4': 'Chọn đối tượng',
        'reports.new_chat': 'Mở luồng phân tích mới',
        'reports.placeholder': 'Hỏi AI để tạo báo cáo, ví dụ: "Xu hướng doanh thu theo danh mục"',
        'reports.strategic_summary': 'Chiến lược & Kiến nghị hành động',
        'reports.analysis': 'Phân tích cội nguồn & Dữ liệu',
        'reports.recommendation': 'Hành động đề xuất',
        'reports.visualization_layer': 'Lớp trực quan hóa chuẩn xác',
        'reports.export': 'Xuất báo cáo',
        'reports.strategic_flow': 'Luồng chiến lược',
        'reports.grid_view': 'Chế độ lưới',
        'reports.share': 'Chia sẻ thông tin',
        'reports.engine_title': 'Hệ thống phân tích Neural',
        'reports.engine_subtitle': 'Phân tích BigQuery chuẩn xác. Tự động liên kết xu hướng thời gian và các lát cắt dữ liệu để tạo báo cáo tức thì.',
        'bi.visualizations': 'Trực quan hóa',
        'bi.data': 'Dữ liệu',
        'bi.format': 'Thiết kế & Định dạng',
        'bi.filters': 'Bộ lọc Dashboard',
        'bi.visuals': 'Trực quan hóa',
        'bi.config': 'Cấu hình',
        'bi.setup': 'Thiết lập',
        'bi.format_tab': 'Định dạng',
        'bi.filters_tab': 'Bộ lọc',
        'bi.active_table': 'Bảng đang chọn',
        'bi.select_table': 'Chọn bảng dữ liệu...',
        'bi.new_widget': 'Widget mới',
        'bi.kpi_card': 'Thẻ KPI',
        'bi.data_table': 'Bảng dữ liệu',
        'bi.slicer': 'Bộ lọc nhanh',
        'bi.date_range': 'Khoảng ngày',
        'bi.search': 'Ô tìm kiếm',
        'bi.no_widget_selected': 'Chưa chọn Widget',
        'bi.no_widget_selected_desc': 'Chọn một widget trên màn hình để cấu hình dữ liệu và logic.',
        'bi.no_data_source': 'Chưa có nguồn dữ liệu',
        'bi.no_data_source_desc': 'Gán một bảng dữ liệu cho widget này trong tab Trực quan hóa.',
        'bi.select_data_table_btn': 'Chọn bảng dữ liệu',
        'bi.data_fields': 'Trường dữ liệu',
        'bi.source': 'Nguồn',
        'bi.change_source': 'Thay đổi nguồn dữ liệu',
        'bi.cross_filtering': 'BẬT LỌC CHÉO',
        'bi.title': 'Tiêu đề',
        'bi.value_format': 'Định dạng giá trị (Trục)',
        'bi.show_legend': 'Hiển thị chú thích',
        'bi.legend_position': 'Vị trí',
        'bi.show_grid': 'Hiển thị lưới',
        'bi.show_labels': 'Hiển thị nhãn',
        'bi.typography': 'Kiểu chữ',
        'bi.font_family': 'Phông chữ',
        'bi.font_size': 'Kích cỡ chữ',
        'bi.border_shadow': 'Viền & Đổ bóng',
        'bi.border_radius': 'Bo góc',
        'bi.show_shadow': 'Hiển thị bóng',
        'bi.chart_colors': 'Màu biểu đồ',
        'bi.reset_palette': 'Đặt lại bảng màu mặc định',
        'bi.widget_filters': 'Bộ lọc Widget',
        'bi.add_filter': 'Thêm bộ lọc',
        'bi.no_filters': 'Chưa áp dụng bộ lọc nào',
        'bi.saving': 'Đang lưu...',
        'bi.auto_saved': 'Đã lưu tự động',
        'bi.clear_filters': 'Xóa bộ lọc',
        'bi.back_to_list': 'Quay lại danh sách',
        'bi.undo': 'Hoàn tác',
        'bi.redo': 'Làm lại',
        'bi.reload_data': 'Tải lại dữ liệu',
        'bi.auto_reload_settings': 'Cài đặt tự động tải lại',
        'bi.disabled': 'Tắt',
        'bi.every_min': 'Mỗi {mins} phút',
        'bi.every_mins': 'Mỗi {mins} phút',
        'bi.export_pdf': 'Xuất PDF',
        'bi.export_image': 'Xuất hình ảnh',
        'bi.toggle_visual_builder': 'Bật/tắt trình thiết kế',
        'bi.workspace': 'Làm việc',
        'bi.fields': 'Trường dữ liệu',
        'bi.dashboards_title': 'Bảng điều khiển',
        'bi.unfiled': 'Chưa phân loại',
        'bi.new_folder': 'Thư mục mới',
        'bi.new_dashboard': 'Bảng điều khiển mới',
        'bi.confirm_delete': 'Xác nhận xóa',
        'bi.delete_desc': 'Bạn có chắc chắn muốn xóa "{title}"? Hành động này không thể hoàn tác.',
        'bi.delete_btn': 'XÓA',
        'bi.cancel_btn': 'HỦY BỎ',
        'bi.folder_name_placeholder': 'Tên thư mục...',
        'bi.move_to_root': 'Di chuyển ra ngoài cùng',
        'bi.add_calc_field': 'Trường tính toán',
        'bi.add_btn': 'THÊM',
        'bi.save_btn': 'Lưu',
        'bi.cancel_small': 'Hủy',
        'bi.quick_measures': 'Số đo nhanh',
        'bi.selection_mode': 'Chế độ chọn',
        'bi.multi_select': 'Chọn nhiều',
        'bi.single_select': 'Chọn một',
        'bi.global_filter_bar': 'Thanh lọc toàn cục',
        'bi.pin_to_top': 'Ghim lên đầu báo cáo',
        'bi.dropdown_mode': 'Chế độ danh sách thả',
        'bi.compact_view': 'Chế độ xem thu gọn',
        'bi.show_select_all': 'Hiển thị "Chọn tất cả"',
        'bi.quick_toggle': 'Bật/tắt nhanh tất cả tùy chọn',
        'bi.series': 'Chuỗi',
        'bi.default': 'Mặc định',
        'bi.no_widget_selected_desc_start': 'Chọn một widget trên trang để cấu hình',
        'bi.config_data': 'dữ liệu',
        'bi.style': 'kiểu dáng',
        'bi.welcome': 'Chào mừng đến với Dashboard Studio',
        'bi.create_new_dashboard': 'Tạo Bảng điều khiển mới',
        'bi.collapse_left_panel': 'Thu gọn bảng bên trái',
        'bi.expand_left_panel': 'Mở rộng bảng bên trái',
        'bi.collapse_right_panel': 'Thu gọn bảng bên phải',
        'bi.expand_right_panel': 'Mở rộng bảng bên phải',
        'bi.filters_label': 'Bộ lọc',
        'bi.move_to_canvas': 'Chuyển lại về trang thiết kế',
        'bi.add_from_canvas': 'Thêm bộ lọc từ trang thiết kế',
        'bi.add_btn_small': 'Thêm',
        'bi.duplicate_page': 'Nhân bản trang',
        'bi.delete_page': 'Xóa trang',
        'bi.add_new_page': 'Thêm trang mới',
        'bi.delete_page_desc': 'Bạn có chắc chắn muốn xóa trang "{title}" không? Tất cả widget trên trang này sẽ bị xóa. Hành động này không thể hoàn tác.',
    }
};

export const useLanguageStore = create<LanguageState>()(
    persist(
        (set, get) => ({
            language: 'en',
            setLanguage: (lang) => set({ language: lang }),
            t: (key) => {
                const { language } = get();
                return translations[language][key] || key;
            }
        }),
        {
            name: 'app-language',
        }
    )
);
