
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'en' | 'vi';

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, vars?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.connections': 'Connections',
        'nav.tables': 'Data Assets',
        'nav.reports': 'Ask AI',
        'nav.data_modeling': 'Data Modeling',
        'nav.bi': 'Dashboard Studio',
        'nav.ai_config': 'AI Settings',
        'nav.users': 'Users',
        'nav.sign_out': 'Sign Out',
        'nav.locked_tooltip': 'Add a connection first',
        'sys.status': 'System Status',
        'sys.active': 'Pipeline established. AI analysis active.',
        'sys.pending': 'Neural link pending. Connect your data warehouse.',
        'conn.title': 'Data Gateways',
        'conn.subtitle': 'Provision secure pipelines to your enterprise data warehouses',
        'conn.search_placeholder': 'Search gateways...',
        'conn.new_pipeline': 'New Pipeline',
        'conn.stat.total_connections': 'Total Connections',
        'conn.stat.active_syncs': 'Active Syncs',
        'conn.stat.total_tables': 'Linked Tables',
        'conn.stat.system_health': 'System Health',
        'conn.empty_title': 'No Connections Found',
        'conn.empty_subtitle': 'Start by connecting your first data source. We support BigQuery, Snowflake, and more to bring your data to life.',
        'conn.empty_button': 'Get Started Now',
        'conn.card.health': 'Health',
        'conn.card.optimal': 'Optimal',
        'conn.card.objects': 'Objects',
        'conn.wizard.step1': 'Configure Gateway',
        'conn.wizard.step2': 'Identity Verification',
        'conn.wizard.step3': 'Target Environment',
        'conn.wizard.step4': 'Object Selection',
        'reports.new_chat': 'New AI Analysis',
        'reports.placeholder': 'Ask AI to generate a report, e.g. "Revenue trend by category"',
        'reports.strategic_summary': 'Strategic Executive Summary',
        'reports.analysis': 'Root Cause & Data Analysis',
        'reports.recommendation': 'Recommended Actions',
        'reports.visualization_layer': 'Precision Visualization Layer',
        'reports.export': 'Export Report',
        'reports.strategic_flow': 'Strategic Flow',
        'reports.grid_view': 'Grid View',
        'reports.share': 'Share Insight',
        'reports.engine_title': 'Neural Analysis Engine',
        'reports.engine_subtitle': 'Precision BigQuery analysis. Automatically links time trends and categorical dimensions for instant visualization.',
        'bi.visualizations': 'Visualizations',
        'bi.data': 'Data Views',
        'bi.format': 'Design & Style',
        'bi.filters': 'Dashboard Filters',
        'bi.visuals': 'Visuals',
        'bi.config': 'Config',
        'bi.setup': 'Setup',
        'bi.format_tab': 'Format',
        'bi.filters_tab': 'Filters',
        'bi.active_table': 'Active Table',
        'bi.select_table': 'Select data table...',
        'bi.new_widget': 'New Widget',
        'bi.kpi_card': 'KPI Card',
        'bi.data_table': 'Data Table',
        'bi.slicer': 'Slicer',
        'bi.date_range': 'Date Range',
        'bi.search': 'Search Box',
        'bi.no_widget_selected': 'No Widget Selected',
        'bi.no_widget_selected_desc': 'Select a widget on the canvas to configure its data fields and logic.',
        'bi.no_data_source': 'No Data Source',
        'bi.no_data_source_desc': 'Assign a data table to this widget in the Visuals tab.',
        'bi.select_data_table_btn': 'Select Data Table',
        'bi.data_fields': 'Data Fields',
        'bi.source': 'Source',
        'bi.change_source': 'Change Data Source',
        'bi.cross_filtering': 'ENABLE CROSS-FILTERING',
        'bi.title': 'Title',
        'bi.value_format': 'Value Format (Axis)',
        'bi.show_legend': 'Show Legend',
        'bi.legend_position': 'Position',
        'bi.show_grid': 'Show Grid',
        'bi.show_labels': 'Show Labels',
        'bi.typography': 'Typography',
        'bi.font_family': 'Font Family',
        'bi.font_size': 'Font Size',
        'bi.border_shadow': 'Border & Shadow',
        'bi.border_radius': 'Border Radius',
        'bi.show_shadow': 'Show Shadow',
        'bi.chart_colors': 'Chart Colors',
        'bi.reset_palette': 'Reset to Default Palette',
        'bi.widget_filters': 'Widget Filters',
        'bi.add_filter': 'Add Filter',
        'bi.no_filters': 'No filters applied',
        'bi.saving': 'Saving...',
        'bi.auto_saved': 'Auto-saved',
        'bi.clear_filters': 'Clear Filters',
        'bi.back_to_list': 'Back to List',
        'bi.undo': 'Undo',
        'bi.redo': 'Redo',
        'bi.reload_data': 'Reload Data',
        'bi.auto_reload_settings': 'Auto-reload Settings',
        'bi.disabled': 'Disabled',
        'bi.every_min': 'Every {mins} min',
        'bi.every_mins': 'Every {mins} mins',
        'bi.export_pdf': 'Export PDF',
        'bi.export_image': 'Export Image',
        'bi.toggle_visual_builder': 'Toggle Visual Builder',
        'bi.workspace': 'Workspace',
        'bi.fields': 'Fields',
        'bi.dashboards_title': 'Dashboards',
        'bi.unfiled': 'Unfiled',
        'bi.new_folder': 'New Folder',
        'bi.new_dashboard': 'New Dashboard',
        'bi.confirm_delete': 'Confirm Delete',
        'bi.delete_desc': 'Are you sure you want to delete "{title}"? This cannot be undone.',
        'bi.delete_btn': 'DELETE',
        'bi.cancel_btn': 'CANCEL',
        'bi.folder_name_placeholder': 'Folder name...',
        'bi.move_to_root': 'Move to root',
        'bi.add_calc_field': 'Calculated Fields',
        'bi.add_btn': 'ADD',
        'bi.save_btn': 'Save',
        'bi.cancel_small': 'Cancel',
        'bi.quick_measures': 'Quick Measures',
        'bi.selection_mode': 'Selection Mode',
        'bi.multi_select': 'Multiple Selection',
        'bi.single_select': 'Single Selection',
        'bi.global_filter_bar': 'Global Filter Bar',
        'bi.pin_to_top': 'Pin to top of report',
        'bi.dropdown_mode': 'Dropdown Mode',
        'bi.compact_view': 'Compact selection view',
        'bi.show_select_all': 'Show "Select All"',
        'bi.quick_toggle': 'Quickly toggle all options',
        'bi.series': 'Series',
        'bi.default': 'Default',
        'bi.no_widget_selected_desc_start': 'Select a widget on the canvas to configure its',
        'bi.config_data': 'data',
        'bi.style': 'style',
        'bi.welcome': 'Welcome to Dashboard Studio',
        'bi.create_new_dashboard': 'Create New Dashboard',
        'bi.collapse_left_panel': 'Collapse Left Panel',
        'bi.expand_left_panel': 'Expand Left Panel',
        'bi.collapse_right_panel': 'Collapse Right Panel',
        'bi.expand_right_panel': 'Expand Right Panel',
        'bi.filters_label': 'Filters',
        'bi.move_to_canvas': 'Move back to Canvas',
        'bi.add_from_canvas': 'Add filter from Canvas',
        'bi.add_btn_small': 'Add',
        'bi.duplicate_page': 'Duplicate Page',
        'bi.duplicate_dashboard': 'Duplicate Dashboard',
        'bi.delete_page': 'Delete Page',
        'bi.add_new_page': 'Add New Page',
        'bi.delete_page_desc': 'Are you sure you want to delete page "{title}"? All widgets on this page will be removed. This cannot be undone.',
        'bi.cf.title': 'Conditional Formatting Rules',
        'bi.cf.metric': 'Metric',
        'bi.cf.rules_hint': 'Rules are evaluated top-down. First match wins.',
        'bi.cf.apply_preset': 'Apply preset...',
        'bi.cf.preset_traffic': 'Traffic (Text)',
        'bi.cf.preset_stoplight': 'Stoplight (Bg)',
        'bi.cf.preset_heatmap': 'Heatmap',
        'bi.cf.recommendations': 'Recommendations',
        'bi.cf.add_rule': '+ Add Rule',
        'bi.cf.rule': 'Rule #{index}',
        'bi.cf.remove': 'Remove',
        'bi.cf.operator': 'Operator',
        'bi.cf.greater_than': '> Greater Than',
        'bi.cf.less_than': '< Less Than',
        'bi.cf.equal': '= Equal',
        'bi.cf.between': 'Between',
        'bi.cf.compare_type': 'Compare Type',
        'bi.cf.fixed_number': 'Fixed Number',
        'bi.cf.metric_total': 'Metric / Total',
        'bi.cf.formula': 'Formula',
        'bi.cf.value': 'Value',
        'bi.cf.threshold_placeholder': 'Enter threshold...',
        'bi.cf.formula_placeholder': 'e.g. ROW_TOTAL * 0.1 or SAFE_DIV(VALUE, GRAND_TOTAL) * 100',
        'bi.cf.formula_ok': 'Formula syntax looks good',
        'bi.cf.hide_helpers': 'Hide Helpers',
        'bi.cf.show_helpers': 'Show Helpers',
        'bi.cf.target_metric': 'Target Metric',
        'bi.cf.target_scope': 'Target Scope',
        'bi.cf.scope_same_cell': 'Same Cell',
        'bi.cf.scope_same_row_total': 'Same Row Total',
        'bi.cf.scope_same_column_total': 'Same Column Total',
        'bi.cf.scope_grand_total': 'Grand Total',
        'bi.cf.variables': 'Variables',
        'bi.cf.functions': 'Functions',
        'bi.cf.lower_bound': 'Lower Bound',
        'bi.cf.upper_bound': 'Upper Bound',
        'bi.cf.color_style': 'Color Style',
        'bi.cf.icon': 'Icon',
        'bi.cf.green_text': 'Green Text',
        'bi.cf.red_text': 'Red Text',
        'bi.cf.amber_text': 'Amber Text',
        'bi.cf.white_text': 'White Text',
        'bi.cf.green_bg': 'Green Background',
        'bi.cf.red_bg': 'Red Background',
        'bi.cf.amber_bg': 'Amber Background',
        'bi.cf.no_icon': 'No Icon',
        'bi.cf.icon_up': 'Up',
        'bi.cf.icon_down': 'Down',
        'bi.cf.icon_flat': 'Flat',
        'bi.cf.icon_alert': 'Alert',
        'bi.cf.icon_star': 'Star',
        'bi.cf.no_rules': 'No rules yet. Click {addRule} to start.',
        'bi.cf.recommended_title': 'Recommended Rules',
        'bi.cf.recommended_subtitle': 'One click to apply for metric {metric}',
        'bi.cf.quick_apply_title': 'Recommendations (Quick Apply)',
        'bi.cf.helpers_always_on': 'Structure + AI helpers are always enabled',
        'bi.cf.struct.title': 'Formula Structures',
        'bi.cf.struct.hint': 'Click one template to quickly set formula structure.',
        'bi.cf.struct.share_threshold': 'Share Threshold',
        'bi.cf.struct.share_threshold_note': 'Mark values above a share threshold of row total.',
        'bi.cf.struct.column_baseline': 'Column Baseline',
        'bi.cf.struct.column_baseline_note': 'Compare against a derived baseline from column total.',
        'bi.cf.struct.grand_total_share': 'Grand Total Share',
        'bi.cf.struct.grand_total_share_note': 'Scale thresholds relative to grand total.',
        'bi.cf.struct.safe_ratio': 'Safe Ratio',
        'bi.cf.struct.safe_ratio_note': 'Compute ratio safely with divide-by-zero protection.',
        'bi.cf.struct.clamp_range': 'Clamp Range',
        'bi.cf.struct.clamp_range_note': 'Limit values inside a safe min-max range.',
        'bi.cf.rec.high_share_title': 'High Share (> 10% Grand Total)',
        'bi.cf.rec.high_share_desc': 'Highlight cells contributing more than 10% of the grand total.',
        'bi.cf.rec.row_outlier_title': 'Row Outlier (> 1.5x Row Total)',
        'bi.cf.rec.row_outlier_desc': 'Mark values that are unusually high within the same row.',
        'bi.cf.rec.column_baseline_title': 'Above Column Baseline',
        'bi.cf.rec.column_baseline_desc': 'Color cells above estimated column total baseline.',
        'bi.cf.rec.drop_vs_row_title': 'Drop Vs Row Total (< 8%)',
        'bi.cf.rec.drop_vs_row_desc': 'Flag weak cells under 8% of row total.',
        'bi.cf.rec.safe_margin_title': 'Safe Margin (Ratio > 20%)',
        'bi.cf.rec.safe_margin_desc': 'Use safe division to avoid divide-by-zero while comparing margins.',
        'bi.cf.ai.title': 'AI Formula Assistant',
        'bi.cf.ai.placeholder': 'Example: warn when VALUE is over 20% of ROW_TOTAL',
        'bi.cf.ai.generate': 'AI Generate',
        'bi.cf.ai.generating': 'Generating...',
        'bi.cf.ai.target_rule': 'Target Rule #{index}',
        'bi.cf.ai.prompt_required': 'Enter a prompt for AI formula generation.',
        'bi.cf.ai.no_variables': 'No formula variables available for this metric.',
        'bi.cf.ai.invalid_formula': 'Generated formula is invalid: {error}',
        'bi.cf.ai.generated_by': 'Generated by {provider} • {model}',
        'bi.cf.ai.generate_failed': 'Unable to generate formula right now. Please try again.',
        'share.title': 'Share Access',
        'share.subtitle': 'Identity & Permission Provisioning',
        'share.user_email': 'User Email Address',
        'share.email_placeholder': 'collaborator@yourcompany.com',
        'share.resource_name_purpose': 'Resource Name & Purpose',
        'share.folder': 'Folder',
        'share.container_access': 'Container Access',
        'share.dashboard': 'Dashboard',
        'share.configured': 'Configured',
        'share.not_configured': 'Not configured',
        'share.cancel': 'Cancel',
        'share.confirm_save': 'Confirm & Save Access',
        'share.invalid_email': 'Please enter a valid corporate email.',
        'share.dont_share': "Don't Share",
        'share.viewer': 'Viewer',
        'share.editor': 'Editor',
        'share.admin': 'Admin',
        'share.rls_config': 'RLS Configuration',
        'share.set_permission_to_configure_rls': 'Set permission from "Don\'t Share" to configure RLS.',
        'share.allowed_pages': 'Allowed Pages',
        'share.rules': 'Rules',
        'share.add_rule': '+ Add Rule',
        'share.no_rule_yet': 'No rule yet. Add at least one rule for data scoping.',
        'share.confirm_dashboard': 'Confirm Dashboard',
        'share.no_dashboard_available': 'No dashboard available for RLS config.',
        'share.rule': 'Rule #{index}',
        'share.remove': 'Remove',
        'share.simple': 'Simple',
        'share.advanced': 'Advanced',
        'share.select_field': 'Select field',
        'share.value': 'Value',
        'share.value2': 'Second value',
        'share.values_csv': 'Value1, Value2, Value3',
        'dm.title': 'Data Modeling',
        'dm.semantic_layer': 'Semantic layer',
        'dm.read_only': 'Read only: Admin or Editor role is required to modify relationships',
        'dm.list_view': 'List View',
        'dm.diagram_view': 'Diagram View',
        'dm.refresh': 'Refresh',
        'dm.search_tables': 'Search tables...',
        'dm.dataset': 'dataset',
        'dm.auto_detect_relationship': 'Auto Detect Relationship',
        'dm.detecting': 'Detecting...',
        'dm.create_relationship': 'Create Relationship',
        'dm.table_a': 'Table A',
        'dm.column_a': 'Column A',
        'dm.table_b': 'Table B',
        'dm.column_b': 'Column B',
        'dm.single': 'Single',
        'dm.both': 'Both',
        'dm.cancel': 'Cancel',
        'dm.save_relationship': 'Save Relationship',
        'dm.columns': 'Columns',
        'dm.auto_detect_suggestions': 'Auto Detect Suggestions',
        'dm.reject_selected': 'Reject Selected',
        'dm.accept_selected': 'Accept Selected',
        'dm.no_suggestion': 'No suggestion. Click Auto Detect Relationship.',
        'dm.reject': 'Reject',
        'dm.accept': 'Accept',
        'dm.relationships': 'Relationships',
        'dm.no_relationships': 'No relationships yet.',
        'dm.delete': 'Delete',
        'dm.read_only_diagram': 'Read only: only Admin/Editor can create relationships',
        'dm.relationship_type': 'Relationship Type',
        'dm.cross_filter_direction': 'Cross Filter Direction',
        'dm.close': 'Close',
        'dm.save': 'Save',
        'dm.right_click_hint': 'Right click to edit relationship',
        'nav.logs': 'Logs',
        'lang.english': 'English',
        'lang.vietnamese': 'Vietnamese',
        'sidebar.hide': 'Hide Sidebar',
        'theme.switch_light': 'Switch to Light Mode',
        'theme.switch_dark': 'Switch to Dark Mode',
        'confirm.confirm': 'Confirm',
        'confirm.cancel': 'Cancel',
        'users.alert': 'System Alert',
        'users.title': 'Team Management',
        'users.subtitle': 'Configure workspace autonomy and role-based access protocols',
        'users.invite': 'Invite New Member',
        'users.member_identity': 'Member Identity',
        'users.access_token': 'Access Token',
        'users.authority': 'Authority',
        'users.status': 'Status',
        'users.provisioned': 'Provisioned',
        'users.ops': 'Ops',
        'users.standard': 'Standard',
        'users.scale': 'Scale',
        'users.utc': 'UTC TIMESTAMP',
        'users.restrict_access': 'Restrict Access',
        'users.grant_access': 'Grant Access',
        'users.edit_member': 'Edit Member',
        'users.provisioning_loading': 'Provisioning Access Identity',
        'users.provisioning_title': 'Member Provisioning',
        'users.provisioning_subtitle': 'Identity & Permissions Protocol',
        'users.name_identity': 'Member Name Identity',
        'users.email_endpoint': 'Corporate Endpoint (Email)',
        'users.authorization_node': 'System Authorization Node',
        'users.viewer_readonly': 'Viewer (Read Only)',
        'users.editor_build': 'Editor (Build Access)',
        'users.admin_full': 'Admin (Full Control)',
        'users.dashboard_access': 'Granular Dashboard Access',
        'users.assets_found': '{count} Assets Found',
        'users.no_dashboards': 'No dashboards found to assign.',
        'users.provision_role': 'Provision individual role',
        'users.dont_share': "Don't Share",
        'users.security_protocol': 'Security Protocol',
        'users.security_note': 'Privileges are applied instantly upon account activation.',
        'users.abort_protocol': 'Abort Protocol',
        'users.update_identity': 'Update Identity Package',
        'users.dispatch_identity': 'Dispatch Identity Package',
        'users.unit': 'Unit',
        'users.updated_permissions': 'Permissions updated for {email}',
        'users.failed_update': 'Failed to update user',
        'users.invite_sent': 'Invitation sent and permissions provisioned for {email}',
        'users.invite_offline': 'Invitation sent for {email} (offline mode)',
        'users.err_corporate_only': 'Access restricted: Only corporate email accounts can be invited.',
        'users.err_domain_mismatch': 'Domain Mismatch: You can only invite users with @{domain} emails to this workspace.',
        'users.err_exists': '{email} is already registered in this workspace.',
        'users.note': 'Note',
        'users.tags': 'Tags',
        'users.note_placeholder': 'Add internal notes for this member (visibility, ownership, context...)',
        'users.tags_placeholder': 'Type a tag and press Enter...',
        'users.tags_hint': 'No tags yet',
        'users.max_tags': 'Maximum 20 tags per member',
        'ai.saved': 'AI key settings saved.',
        'ai.neural_hub': 'Neural Hub',
        'ai.subtitle': 'Configure access keys for top AI engines. Enter your key once and start exploring data.',
        'ai.save_neural': 'Save Neural Settings',
        'ai.access_key': 'API Access Key',
        'ai.test_connection': 'Test Connection',
        'ai.configured': 'Configured',
        'ai.no_key': "Don't have a key?",
        'ai.get_key': 'Get API key for {name}',
        'ai.available_engines': 'Available Engines',
        'ai.free': 'Free',
        'ai.footer': '360DATA NEURAL FABRIC • VERSION 2.0',
        'ai.provider.google_desc': 'Use Gemini 2.5 Flash & Pro.',
        'ai.provider.openai_desc': 'Use GPT-5.1 for high-accuracy generation.',
        'ai.provider.anthropic_desc': 'Use Claude Sonnet 4 for coding and reasoning.',
    },
    vi: {
        'nav.connections': 'Kết nối',
        'nav.tables': 'Tài sản dữ liệu',
        'nav.reports': 'Hỏi đáp AI',
        'nav.data_modeling': 'Data Modeling',
        'nav.bi': 'Thiết kế Dashboard',
        'nav.ai_config': 'Cài đặt AI',
        'nav.users': 'Người dùng',
        'nav.sign_out': 'Đăng xuất',
        'nav.locked_tooltip': 'Vui lòng thêm kết nối trước',
        'sys.status': 'Trạng thái hệ thống',
        'sys.active': 'Đường ống đã thiết lập. AI đang phân tích.',
        'sys.pending': 'Chờ kết nối. Vui lòng kết nối kho dữ liệu.',
        'conn.title': 'Cổng kết nối dữ liệu',
        'conn.subtitle': 'Thiết lập các đường ống dữ liệu bảo mật tới kho dữ liệu của doanh nghiệp',
        'conn.search_placeholder': 'Tìm kiếm kết nối...',
        'conn.new_pipeline': 'Kết nối mới',
        'conn.stat.total_connections': 'Tổng số kết nối',
        'conn.stat.active_syncs': 'Đang đồng bộ',
        'conn.stat.total_tables': 'Số lượng bảng',
        'conn.stat.system_health': 'Tình trạng hệ thống',
        'conn.empty_title': 'Chưa có kết nối nào',
        'conn.empty_subtitle': 'Bắt đầu bằng cách kết nối với nguồn dữ liệu đầu tiên của bạn. Chúng tôi hỗ trợ BigQuery, Snowflake và nhiều nguồn khác.',
        'conn.empty_button': 'Bắt đầu ngay',
        'conn.card.health': 'Trạng thái',
        'conn.card.optimal': 'Hoạt động tốt',
        'conn.card.objects': 'Đối tượng',
        'conn.wizard.step1': 'Cấu hình kết nối',
        'conn.wizard.step2': 'Xác thực danh tính',
        'conn.wizard.step3': 'Môi trường mục tiêu',
        'conn.wizard.step4': 'Chọn đối tượng',
        'reports.new_chat': 'Mở luồng phân tích mới',
        'reports.placeholder': 'Hỏi AI để tạo báo cáo, ví dụ: "Xu hướng doanh thu theo danh mục"',
        'reports.strategic_summary': 'Chiến lược & Kiến nghị hành động',
        'reports.analysis': 'Phân tích cội nguồn & Dữ liệu',
        'reports.recommendation': 'Hành động đề xuất',
        'reports.visualization_layer': 'Lớp trực quan hóa chuẩn xác',
        'reports.export': 'Xuất báo cáo',
        'reports.strategic_flow': 'Luồng chiến lược',
        'reports.grid_view': 'Chế độ lưới',
        'reports.share': 'Chia sẻ thông tin',
        'reports.engine_title': 'Hệ thống phân tích Neural',
        'reports.engine_subtitle': 'Phân tích BigQuery chuẩn xác. Tự động liên kết xu hướng thời gian và các lát cắt dữ liệu để tạo báo cáo tức thì.',
        'bi.visualizations': 'Trực quan hóa',
        'bi.data': 'Dữ liệu',
        'bi.format': 'Thiết kế & Định dạng',
        'bi.filters': 'Bộ lọc Dashboard',
        'bi.visuals': 'Trực quan hóa',
        'bi.config': 'Cấu hình',
        'bi.setup': 'Thiết lập',
        'bi.format_tab': 'Định dạng',
        'bi.filters_tab': 'Bộ lọc',
        'bi.active_table': 'Bảng đang chọn',
        'bi.select_table': 'Chọn bảng dữ liệu...',
        'bi.new_widget': 'Widget mới',
        'bi.kpi_card': 'Thẻ KPI',
        'bi.data_table': 'Bảng dữ liệu',
        'bi.slicer': 'Bộ lọc nhanh',
        'bi.date_range': 'Khoảng ngày',
        'bi.search': 'Ô tìm kiếm',
        'bi.no_widget_selected': 'Chưa chọn Widget',
        'bi.no_widget_selected_desc': 'Chọn một widget trên màn hình để cấu hình dữ liệu và logic.',
        'bi.no_data_source': 'Chưa có nguồn dữ liệu',
        'bi.no_data_source_desc': 'Gán một bảng dữ liệu cho widget này trong tab Trực quan hóa.',
        'bi.select_data_table_btn': 'Chọn bảng dữ liệu',
        'bi.data_fields': 'Trường dữ liệu',
        'bi.source': 'Nguồn',
        'bi.change_source': 'Thay đổi nguồn dữ liệu',
        'bi.cross_filtering': 'BẬT LỌC CHÉO',
        'bi.title': 'Tiêu đề',
        'bi.value_format': 'Định dạng giá trị (Trục)',
        'bi.show_legend': 'Hiển thị chú thích',
        'bi.legend_position': 'Vị trí',
        'bi.show_grid': 'Hiển thị lưới',
        'bi.show_labels': 'Hiển thị nhãn',
        'bi.typography': 'Kiểu chữ',
        'bi.font_family': 'Phông chữ',
        'bi.font_size': 'Kích cỡ chữ',
        'bi.border_shadow': 'Viền & Đổ bóng',
        'bi.border_radius': 'Bo góc',
        'bi.show_shadow': 'Hiển thị bóng',
        'bi.chart_colors': 'Màu biểu đồ',
        'bi.reset_palette': 'Đặt lại bảng màu mặc định',
        'bi.widget_filters': 'Bộ lọc Widget',
        'bi.add_filter': 'Thêm bộ lọc',
        'bi.no_filters': 'Chưa áp dụng bộ lọc nào',
        'bi.saving': 'Đang lưu...',
        'bi.auto_saved': 'Đã lưu tự động',
        'bi.clear_filters': 'Xóa bộ lọc',
        'bi.back_to_list': 'Quay lại danh sách',
        'bi.undo': 'Hoàn tác',
        'bi.redo': 'Làm lại',
        'bi.reload_data': 'Tải lại dữ liệu',
        'bi.auto_reload_settings': 'Cài đặt tự động tải lại',
        'bi.disabled': 'Tắt',
        'bi.every_min': 'Mỗi {mins} phút',
        'bi.every_mins': 'Mỗi {mins} phút',
        'bi.export_pdf': 'Xuất PDF',
        'bi.export_image': 'Xuất hình ảnh',
        'bi.toggle_visual_builder': 'Bật/tắt trình thiết kế',
        'bi.workspace': 'Làm việc',
        'bi.fields': 'Trường dữ liệu',
        'bi.dashboards_title': 'Bảng điều khiển',
        'bi.unfiled': 'Chưa phân loại',
        'bi.new_folder': 'Thư mục mới',
        'bi.new_dashboard': 'Bảng điều khiển mới',
        'bi.confirm_delete': 'Xác nhận xóa',
        'bi.delete_desc': 'Bạn có chắc chắn muốn xóa "{title}"? Hành động này không thể hoàn tác.',
        'bi.delete_btn': 'XÓA',
        'bi.cancel_btn': 'HỦY BỎ',
        'bi.folder_name_placeholder': 'Tên thư mục...',
        'bi.move_to_root': 'Di chuyển ra ngoài cùng',
        'bi.add_calc_field': 'Trường tính toán',
        'bi.add_btn': 'THÊM',
        'bi.save_btn': 'Lưu',
        'bi.cancel_small': 'Hủy',
        'bi.quick_measures': 'Số đo nhanh',
        'bi.selection_mode': 'Chế độ chọn',
        'bi.multi_select': 'Chọn nhiều',
        'bi.single_select': 'Chọn một',
        'bi.global_filter_bar': 'Thanh lọc toàn cục',
        'bi.pin_to_top': 'Ghim lên đầu báo cáo',
        'bi.dropdown_mode': 'Chế độ danh sách thả',
        'bi.compact_view': 'Chế độ xem thu gọn',
        'bi.show_select_all': 'Hiển thị "Chọn tất cả"',
        'bi.quick_toggle': 'Bật/tắt nhanh tất cả tùy chọn',
        'bi.series': 'Chuỗi',
        'bi.default': 'Mặc định',
        'bi.no_widget_selected_desc_start': 'Chọn một widget trên trang để cấu hình',
        'bi.config_data': 'dữ liệu',
        'bi.style': 'kiểu dáng',
        'bi.welcome': 'Chào mừng đến với Dashboard Studio',
        'bi.create_new_dashboard': 'Tạo Bảng điều khiển mới',
        'bi.collapse_left_panel': 'Thu gọn bảng bên trái',
        'bi.expand_left_panel': 'Mở rộng bảng bên trái',
        'bi.collapse_right_panel': 'Thu gọn bảng bên phải',
        'bi.expand_right_panel': 'Mở rộng bảng bên phải',
        'bi.filters_label': 'Bộ lọc',
        'bi.move_to_canvas': 'Chuyển lại về trang thiết kế',
        'bi.add_from_canvas': 'Thêm bộ lọc từ trang thiết kế',
        'bi.add_btn_small': 'Thêm',
        'bi.duplicate_page': 'Nhân bản trang',
        'bi.duplicate_dashboard': 'Nhân bản dashboard',
        'bi.delete_page': 'Xóa trang',
        'bi.add_new_page': 'Thêm trang mới',
        'bi.delete_page_desc': 'Bạn có chắc chắn muốn xóa trang "{title}" không? Tất cả widget trên trang này sẽ bị xóa. Hành động này không thể hoàn tác.',
        'bi.cf.title': 'Quy tắc định dạng có điều kiện',
        'bi.cf.metric': 'Chỉ số',
        'bi.cf.rules_hint': 'Quy tắc được đánh giá từ trên xuống. Quy tắc khớp đầu tiên sẽ được áp dụng.',
        'bi.cf.apply_preset': 'Áp dụng mẫu...',
        'bi.cf.preset_traffic': 'Traffic (Màu chữ)',
        'bi.cf.preset_stoplight': 'Stoplight (Nền)',
        'bi.cf.preset_heatmap': 'Heatmap',
        'bi.cf.recommendations': 'Gợi ý',
        'bi.cf.add_rule': '+ Thêm quy tắc',
        'bi.cf.rule': 'Quy tắc #{index}',
        'bi.cf.remove': 'Xóa',
        'bi.cf.operator': 'Toán tử',
        'bi.cf.greater_than': '> Lớn hơn',
        'bi.cf.less_than': '< Nhỏ hơn',
        'bi.cf.equal': '= Bằng',
        'bi.cf.between': 'Nằm trong khoảng',
        'bi.cf.compare_type': 'Kiểu so sánh',
        'bi.cf.fixed_number': 'Số cố định',
        'bi.cf.metric_total': 'Chỉ số / Tổng',
        'bi.cf.formula': 'Công thức',
        'bi.cf.value': 'Giá trị',
        'bi.cf.threshold_placeholder': 'Nhập ngưỡng...',
        'bi.cf.formula_placeholder': 'vd: ROW_TOTAL * 0.1 hoặc SAFE_DIV(VALUE, GRAND_TOTAL) * 100',
        'bi.cf.formula_ok': 'Cú pháp công thức hợp lệ',
        'bi.cf.hide_helpers': 'Ẩn trợ giúp',
        'bi.cf.show_helpers': 'Hiện trợ giúp',
        'bi.cf.target_metric': 'Chỉ số mục tiêu',
        'bi.cf.target_scope': 'Phạm vi mục tiêu',
        'bi.cf.scope_same_cell': 'Cùng ô',
        'bi.cf.scope_same_row_total': 'Tổng cùng hàng',
        'bi.cf.scope_same_column_total': 'Tổng cùng cột',
        'bi.cf.scope_grand_total': 'Tổng toàn bộ',
        'bi.cf.variables': 'Biến',
        'bi.cf.functions': 'Hàm',
        'bi.cf.lower_bound': 'Ngưỡng dưới',
        'bi.cf.upper_bound': 'Ngưỡng trên',
        'bi.cf.color_style': 'Kiểu màu',
        'bi.cf.icon': 'Biểu tượng',
        'bi.cf.green_text': 'Chữ xanh',
        'bi.cf.red_text': 'Chữ đỏ',
        'bi.cf.amber_text': 'Chữ vàng',
        'bi.cf.white_text': 'Chữ trắng',
        'bi.cf.green_bg': 'Nền xanh',
        'bi.cf.red_bg': 'Nền đỏ',
        'bi.cf.amber_bg': 'Nền vàng',
        'bi.cf.no_icon': 'Không biểu tượng',
        'bi.cf.icon_up': 'Tăng',
        'bi.cf.icon_down': 'Giảm',
        'bi.cf.icon_flat': 'Đi ngang',
        'bi.cf.icon_alert': 'Cảnh báo',
        'bi.cf.icon_star': 'Đánh dấu sao',
        'bi.cf.no_rules': 'Chưa có quy tắc. Bấm {addRule} để bắt đầu.',
        'bi.cf.recommended_title': 'Quy tắc gợi ý',
        'bi.cf.recommended_subtitle': 'Một cú nhấp để áp dụng cho chỉ số {metric}',
        'bi.cf.quick_apply_title': 'Gợi ý (Áp dụng nhanh)',
        'bi.cf.helpers_always_on': 'Cấu trúc + trợ lý AI luôn được bật',
        'bi.cf.struct.title': 'Cấu trúc công thức',
        'bi.cf.struct.hint': 'Nhấn một mẫu để điền nhanh cấu trúc công thức.',
        'bi.cf.struct.share_threshold': 'Ngưỡng tỷ trọng',
        'bi.cf.struct.share_threshold_note': 'Đánh dấu giá trị vượt ngưỡng tỷ trọng theo tổng hàng.',
        'bi.cf.struct.column_baseline': 'Mốc cột',
        'bi.cf.struct.column_baseline_note': 'So sánh với mốc suy ra từ tổng cột.',
        'bi.cf.struct.grand_total_share': 'Tỷ trọng tổng toàn bộ',
        'bi.cf.struct.grand_total_share_note': 'Đặt ngưỡng theo tỷ lệ của tổng toàn bộ.',
        'bi.cf.struct.safe_ratio': 'Tỷ lệ an toàn',
        'bi.cf.struct.safe_ratio_note': 'Tính tỷ lệ an toàn, tránh chia cho 0.',
        'bi.cf.struct.clamp_range': 'Giới hạn biên',
        'bi.cf.struct.clamp_range_note': 'Giới hạn giá trị trong khoảng min-max an toàn.',
        'bi.cf.rec.high_share_title': 'Tỷ trọng cao (> 10% Tổng toàn bộ)',
        'bi.cf.rec.high_share_desc': 'Tô nổi bật ô đóng góp hơn 10% tổng toàn bộ.',
        'bi.cf.rec.row_outlier_title': 'Ngoại lệ theo hàng (> 1.5x Tổng hàng)',
        'bi.cf.rec.row_outlier_desc': 'Đánh dấu giá trị cao bất thường trong cùng hàng.',
        'bi.cf.rec.column_baseline_title': 'Vượt mốc cột',
        'bi.cf.rec.column_baseline_desc': 'Tô màu ô cao hơn mốc ước lượng theo tổng cột.',
        'bi.cf.rec.drop_vs_row_title': 'Sụt so với tổng hàng (< 8%)',
        'bi.cf.rec.drop_vs_row_desc': 'Đánh dấu ô yếu dưới 8% tổng hàng.',
        'bi.cf.rec.safe_margin_title': 'Biên an toàn (Tỷ lệ > 20%)',
        'bi.cf.rec.safe_margin_desc': 'Dùng chia an toàn để tránh chia cho 0 khi so sánh biên.',
        'bi.cf.ai.title': 'Trợ lý công thức AI',
        'bi.cf.ai.placeholder': 'Ví dụ: cảnh báo khi VALUE lớn hơn 20% ROW_TOTAL',
        'bi.cf.ai.generate': 'AI tạo công thức',
        'bi.cf.ai.generating': 'Đang tạo...',
        'bi.cf.ai.target_rule': 'Quy tắc mục tiêu #{index}',
        'bi.cf.ai.prompt_required': 'Nhập yêu cầu để AI tạo công thức.',
        'bi.cf.ai.no_variables': 'Không có biến công thức cho chỉ số này.',
        'bi.cf.ai.invalid_formula': 'Công thức AI tạo chưa hợp lệ: {error}',
        'bi.cf.ai.generated_by': 'Tạo bởi {provider} • {model}',
        'bi.cf.ai.generate_failed': 'Không thể tạo công thức lúc này. Vui lòng thử lại.',
        'share.title': 'Chia sẻ quyền truy cập',
        'share.subtitle': 'Danh tính & cấp quyền',
        'share.user_email': 'Địa chỉ email người dùng',
        'share.email_placeholder': 'congtacvien@congty.com',
        'share.resource_name_purpose': 'Tên tài nguyên & mục đích',
        'share.folder': 'Thư mục',
        'share.container_access': 'Quyền truy cập thư mục',
        'share.dashboard': 'Dashboard',
        'share.configured': 'Đã cấu hình',
        'share.not_configured': 'Chưa cấu hình',
        'share.cancel': 'Hủy',
        'share.confirm_save': 'Xác nhận & lưu quyền',
        'share.invalid_email': 'Vui lòng nhập email hợp lệ.',
        'share.dont_share': 'Không chia sẻ',
        'share.viewer': 'Người xem',
        'share.editor': 'Biên tập',
        'share.admin': 'Quản trị',
        'share.rls_config': 'Cấu hình RLS',
        'share.set_permission_to_configure_rls': 'Đổi quyền từ "Không chia sẻ" để cấu hình RLS.',
        'share.allowed_pages': 'Trang được phép xem',
        'share.rules': 'Quy tắc',
        'share.add_rule': '+ Thêm quy tắc',
        'share.no_rule_yet': 'Chưa có quy tắc. Thêm ít nhất một quy tắc để giới hạn dữ liệu.',
        'share.confirm_dashboard': 'Xác nhận dashboard',
        'share.no_dashboard_available': 'Không có dashboard để cấu hình RLS.',
        'share.rule': 'Quy tắc #{index}',
        'share.remove': 'Xóa',
        'share.simple': 'Cơ bản',
        'share.advanced': 'Nâng cao',
        'share.select_field': 'Chọn trường',
        'share.value': 'Giá trị',
        'share.value2': 'Giá trị thứ hai',
        'share.values_csv': 'Giá trị1, Giá trị2, Giá trị3',
        'dm.title': 'Mô hình dữ liệu',
        'dm.semantic_layer': 'Lớp semantic',
        'dm.read_only': 'Chỉ đọc: cần quyền Admin hoặc Editor để chỉnh relationship',
        'dm.list_view': 'Dạng danh sách',
        'dm.diagram_view': 'Dạng sơ đồ',
        'dm.refresh': 'Làm mới',
        'dm.search_tables': 'Tìm bảng...',
        'dm.dataset': 'dataset',
        'dm.auto_detect_relationship': 'Tự động phát hiện relationship',
        'dm.detecting': 'Đang phát hiện...',
        'dm.create_relationship': 'Tạo relationship',
        'dm.table_a': 'Bảng A',
        'dm.column_a': 'Cột A',
        'dm.table_b': 'Bảng B',
        'dm.column_b': 'Cột B',
        'dm.single': 'Một chiều',
        'dm.both': 'Hai chiều',
        'dm.cancel': 'Hủy',
        'dm.save_relationship': 'Lưu relationship',
        'dm.columns': 'Cột',
        'dm.auto_detect_suggestions': 'Gợi ý tự động',
        'dm.reject_selected': 'Từ chối đã chọn',
        'dm.accept_selected': 'Chấp nhận đã chọn',
        'dm.no_suggestion': 'Chưa có gợi ý. Nhấn Tự động phát hiện relationship.',
        'dm.reject': 'Từ chối',
        'dm.accept': 'Chấp nhận',
        'dm.relationships': 'Relationships',
        'dm.no_relationships': 'Chưa có relationship.',
        'dm.delete': 'Xóa',
        'dm.read_only_diagram': 'Chỉ đọc: chỉ Admin/Editor mới tạo được relationship',
        'dm.relationship_type': 'Loại relationship',
        'dm.cross_filter_direction': 'Hướng lọc chéo',
        'dm.close': 'Đóng',
        'dm.save': 'Lưu',
        'dm.right_click_hint': 'Nhấp phải để chỉnh relationship',
        'nav.logs': 'Nhật ký',
        'lang.english': 'English',
        'lang.vietnamese': 'Tiếng Việt',
        'sidebar.hide': 'Thu gọn thanh bên',
        'theme.switch_light': 'Chuyển sang giao diện sáng',
        'theme.switch_dark': 'Chuyển sang giao diện tối',
        'confirm.confirm': 'Xác nhận',
        'confirm.cancel': 'Hủy',
        'users.alert': 'Thông báo hệ thống',
        'users.title': 'Quản lý thành viên',
        'users.subtitle': 'Cấu hình quyền truy cập và vai trò trong workspace',
        'users.invite': 'Mời thành viên mới',
        'users.member_identity': 'Định danh thành viên',
        'users.access_token': 'Quyền truy cập',
        'users.authority': 'Phân quyền',
        'users.status': 'Trạng thái',
        'users.provisioned': 'Ngày cấp',
        'users.ops': 'Thao tác',
        'users.standard': 'Tiêu chuẩn',
        'users.scale': 'Quy mô',
        'users.utc': 'MỐC THỜI GIAN UTC',
        'users.restrict_access': 'Hạn chế truy cập',
        'users.grant_access': 'Cấp quyền truy cập',
        'users.edit_member': 'Chỉnh sửa thành viên',
        'users.provisioning_loading': 'Đang cấp quyền truy cập',
        'users.provisioning_title': 'Cấp quyền thành viên',
        'users.provisioning_subtitle': 'Giao thức danh tính & phân quyền',
        'users.name_identity': 'Định danh tên thành viên',
        'users.email_endpoint': 'Email công ty',
        'users.authorization_node': 'Nút phân quyền hệ thống',
        'users.viewer_readonly': 'Viewer (Chỉ xem)',
        'users.editor_build': 'Editor (Xây dựng)',
        'users.admin_full': 'Admin (Toàn quyền)',
        'users.dashboard_access': 'Phân quyền dashboard chi tiết',
        'users.assets_found': '{count} tài sản',
        'users.no_dashboards': 'Không có dashboard để phân quyền.',
        'users.provision_role': 'Cấp quyền theo dashboard',
        'users.dont_share': 'Không chia sẻ',
        'users.security_protocol': 'Giao thức bảo mật',
        'users.security_note': 'Quyền sẽ được áp dụng ngay sau khi tài khoản kích hoạt.',
        'users.abort_protocol': 'Hủy thao tác',
        'users.update_identity': 'Cập nhật gói danh tính',
        'users.dispatch_identity': 'Gửi gói danh tính',
        'users.unit': 'Bộ phận',
        'users.updated_permissions': 'Đã cập nhật quyền cho {email}',
        'users.failed_update': 'Không thể cập nhật người dùng',
        'users.invite_sent': 'Đã gửi mời và cấp quyền cho {email}',
        'users.invite_offline': 'Đã gửi mời cho {email} (chế độ offline)',
        'users.err_corporate_only': 'Chỉ có thể mời email công ty.',
        'users.err_domain_mismatch': 'Sai domain: chỉ mời email @{domain} vào workspace này.',
        'users.err_exists': '{email} đã tồn tại trong workspace.',
        'users.note': 'Ghi chú',
        'users.tags': 'Tag',
        'users.note_placeholder': 'Thêm ghi chú nội bộ cho thành viên này (quyền hạn, phạm vi phụ trách, bối cảnh...)',
        'users.tags_placeholder': 'Nhập tag rồi nhấn Enter...',
        'users.tags_hint': 'Chưa có tag',
        'users.max_tags': 'Tối đa 20 tag cho mỗi thành viên',
        'ai.saved': 'Đã lưu cấu hình API key AI.',
        'ai.neural_hub': 'Trung tâm Neural',
        'ai.subtitle': 'Thiết lập khóa truy cập cho các AI hàng đầu. Nhập key một lần để bắt đầu khám phá dữ liệu.',
        'ai.save_neural': 'Lưu cấu hình Neural',
        'ai.access_key': 'Khóa truy cập API',
        'ai.test_connection': 'Kiểm tra kết nối',
        'ai.configured': 'Đã cấu hình',
        'ai.no_key': 'Chưa có khóa?',
        'ai.get_key': 'Lấy API key cho {name}',
        'ai.available_engines': 'Các engine khả dụng',
        'ai.free': 'Miễn phí',
        'ai.footer': '360DATA NEURAL FABRIC • PHIÊN BẢN 2.0',
        'ai.provider.google_desc': 'Sử dụng Gemini 2.5 Flash & Pro.',
        'ai.provider.openai_desc': 'Sử dụng GPT-5.1 cho độ chính xác cao.',
        'ai.provider.anthropic_desc': 'Sử dụng Claude Sonnet 4 cho coding và suy luận.',
    }
};

export const useLanguageStore = create<LanguageState>()(
    persist(
        (set, get) => ({
            language: 'en',
            setLanguage: (lang) => set({ language: lang }),
            t: (key, vars) => {
                const { language } = get();
                const template = translations[language][key] || translations.en[key] || key;
                if (!vars) return template;
                return Object.entries(vars).reduce((acc, [k, v]) => {
                    return acc.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
                }, template);
            }
        }),
        {
            name: 'app-language',
        }
    )
);
